name: tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [ "8.2", "8.3" ]
                laravel: [ "10", "11", "12", "13" ]
                exclude:
                    - php: "8.2"
                      laravel: "13" # Laravel 13 requires PHP 8.3+

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: curl, gd, mbstring, sqlite
                  coverage: none

            - name: Install dependencies
              run: composer update --no-interaction --no-progress
              env:
                  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

            - name: Run Pint
              run: ./vendor/bin/pint --test

            - name: Run PHPStan
              run: ./vendor/bin/phpstan analyse

            - name: Run tests
              run: ./vendor/bin/pest
